# Generated by Django 2.2.1 on 2019-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
