# Generated by Django 2.2.1 on 2020-01-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190918_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
    ]
