# Generated by Django 2.2.1 on 2019-06-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooltype',
            old_name='ammount_allocated',
            new_name='amount_allocated',
        ),
    ]
