# Generated by Django 2.2.1 on 2019-07-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='death_certs',
            field=models.FileField(blank=True, null=True, upload_to='death_files/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='disability_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
