# Generated by Django 2.2.1 on 2019-07-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190712_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='death_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='death_certs',
        ),
        migrations.AddField(
            model_name='applicant',
            name='death_certs',
            field=models.ManyToManyField(to='applications.File'),
        ),
    ]
