# Generated by Django 2.2.1 on 2019-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190712_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='death_certs',
        ),
        migrations.AddField(
            model_name='applicant',
            name='death_cert_father',
            field=models.FileField(blank=True, null=True, upload_to='death_files/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='death_cert_mother',
            field=models.FileField(blank=True, null=True, upload_to='death_files/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
