# Generated by Django 2.2.1 on 2019-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20190712_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='financial_year',
            field=models.CharField(default='2019/2020', max_length=200),
        ),
    ]
