# Generated by Django 2.2.1 on 2019-07-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20190712_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooltype',
            name='amount_allocated',
        ),
    ]
