# Generated by Django 2.2.1 on 2019-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_schooltype_amount_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
