# Generated by Django 2.2.1 on 2019-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_applicant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='discipline',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=250, null=True),
        ),
    ]
