# Generated by Django 2.2.1 on 2019-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20190716_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_of_gurdian',
            field=models.CharField(max_length=150),
        ),
    ]
