# Generated by Django 2.2.1 on 2019-08-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_cheque'),
        ('applications', '0014_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cheque_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Cheque'),
        ),
    ]
