# Generated by Django 2.2.1 on 2019-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_applicant_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='school@test.com', max_length=254),
        ),
    ]
