# Generated by Django 2.2.1 on 2020-01-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_school_email'),
    ]

    operations = [        
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='financial_year',
            field=models.CharField(default='2020/2021', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='school_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='applications.SchoolType'),
        ),
    ]
