# Generated by Django 2.2.1 on 2019-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_school_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
