# Generated by Django 2.2.1 on 2020-01-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20200113_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='award_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('awarded', 'Awarded'), ('not_awarded', 'Not Awarded')], default='awarded', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalapplicant',
            name='award_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('awarded', 'Awarded'), ('not_awarded', 'Not Awarded')], default='awarded', max_length=200),
        ),
    ]
