# Generated by Django 2.2.1 on 2019-06-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.IntegerField()),
                ('application_start_date', models.DateTimeField()),
                ('application_end_date', models.DateTimeField()),
                ('award_period', models.BooleanField(default=False)),
                ('financial_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.FinancialYear')),
            ],
        ),
    ]
