# Generated by Django 2.2.1 on 2019-07-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_schooltype_amount_allocated'),
        ('accounting', '0002_allocationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCategoryAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.IntegerField()),
                ('financial_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.FinancialYear')),
                ('school_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.SchoolType')),
            ],
        ),
    ]
