# Generated by Django 2.2.1 on 2019-07-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_schoolcategoryallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcategoryallocation',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.FinancialYear'),
        ),
    ]
