# Generated by Django 2.2.1 on 2019-07-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20190713_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcategoryallocation',
            name='school_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.SchoolType'),
        ),
    ]
