# Generated by Django 2.2.1 on 2019-07-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20190713_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolCategoryAllocation',
        ),
    ]
