# Generated by Django 2.2.1 on 2019-07-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_delete_schoolcategoryallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationdetail',
            name='award_period',
        ),
    ]
