# Generated by Django 2.2.1 on 2019-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='start_date',
            field=models.IntegerField(default=2019),
        ),
    ]
