# Generated by Django 2.2.1 on 2019-10-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20190923_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationdetail',
            name='award_period',
            field=models.BooleanField(default=False),
        ),
    ]
